import os
from pathlib import Path

from dotenv import load_dotenv
from pydantic_settings import BaseSettings
from pydantic_settings import SettingsConfigDict


BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PROJECT_DIR = os.path.abspath(os.path.join(BASE_DIR, ".."))
INSTANCE_DIR = os.path.join(BASE_DIR, "instance")
os.makedirs(INSTANCE_DIR, exist_ok=True)

PROJECT_ENV = Path(PROJECT_DIR) / ".env"
BACKEND_ENV = Path(BASE_DIR) / ".env"
load_dotenv(PROJECT_ENV)
load_dotenv(BACKEND_ENV)


class Settings(BaseSettings):
    MONGODB_URL: str
    MONGODB_DATABASE: str
    MONGODB_SERVER_SELECTION_TIMEOUT_MS: int = 5000
    MONGODB_CONNECT_TIMEOUT_MS: int = 5000
    MONGODB_SOCKET_TIMEOUT_MS: int = 20000
    MONGODB_WAIT_QUEUE_TIMEOUT_MS: int = 5000
    MONGODB_MAX_POOL_SIZE: int = 200
    MONGODB_MIN_POOL_SIZE: int = 10
    MONGODB_MAX_IDLE_TIME_MS: int = 60000

    SECRET_KEY: str
    CREDENTIAL_ENCRYPTION_KEY: str | None = None
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60
    ENVIRONMENT: str = "development"

    GUACAMOLE_URL: str | None = None
    GUACAMOLE_PUBLIC_URL: str | None = None
    GUACAMOLE_USER: str | None = None
    GUACAMOLE_PASSWORD: str | None = None
    GUACAMOLE_DATA_SOURCE: str | None = None
    GUACAMOLE_TOKEN_CACHE_SECONDS: int = 300
    REMOTEAPP_BROWSER_LAUNCH_TTL_SECONDS: int = 120
    GUACAMOLE_HTTP_POOL_SIZE: int = 100
    GUACAMOLE_CONNECT_TIMEOUT_SECONDS: float = 3.0
    GUACAMOLE_READ_TIMEOUT_SECONDS: float = 10.0
    GUACAMOLE_VISUAL_QUALITY: str = 'balanced'
    GUACAMOLE_ENABLE_PRINTING: bool = True
    GUACAMOLE_PRINTER_NAME: str = "LR Remote Printer"
    GUACAMOLE_MAX_CONNECTIONS: int = 1
    GUACAMOLE_MAX_CONNECTIONS_PER_USER: int = 1

    PORTAL_HOME_URL: str | None = None
    FRONTEND_URL: str | None = None
    LR_SERVER_URL: str | None = None
    LR_BACKEND_URL: str | None = None
    RDP_PRECHECK_ENABLED: str = "true"
    FILE_TRANSFER_ROOT: str | None = None
    FILE_TRANSFER_MAX_UPLOAD_BYTES: int = 100_000_000
    FILE_TRANSFER_MAX_READ_BYTES: int = 1_000_000
    FLASK_ENV: str | None = None
    CORS_ORIGINS: str | None = None
    SOCKETIO_CORS_ORIGINS: str | None = None
    SOCKETIO_MESSAGE_QUEUE: str | None = None
    SOCKETIO_ASYNC_MODE: str | None = None
    SOCKETIO_PING_INTERVAL_SECONDS: int = 25
    SOCKETIO_PING_TIMEOUT_SECONDS: int = 60
    SOCKETIO_MAX_HTTP_BUFFER_BYTES: int = 1_000_000
    PRINTING_ENABLED: bool = True
    PRINTING_MAX_JOB_SIZE_MB: int = 50
    PRINTING_JOB_TIMEOUT_SECONDS: int = 120
    PRINTING_TEMP_RETENTION_SECONDS: int = 300
    PRINTING_DEFAULT_MODE: str = "ask"
    PRINTING_BROWSER_FALLBACK: bool = True
    PRINTING_CHUNK_SIZE: int = 256 * 1024
    PRINTING_AUTOMATIC: bool = False
    PRINTING_ALLOWED_MODES: str = "ask,default,preview,save,selected"
    PRINTING_SPOOL_ROOT: str | None = None
    LICENSE_VALIDATION_URL: str | None = None
    LICENSE_VALIDATION_TIMEOUT_SECONDS: float = 10.0

    # Multi-tenancy is additive and legacy escape hatches are explicit.
    TENANT_REGISTRATION_ENABLED: bool = True
    AGENT_ENROLLMENT_TOKEN_EXPIRY_SECONDS: int = 900
    AGENT_ENROLLMENT_REQUIRED: bool = True
    AGENT_REQUIRE_MACHINE_BINDING: bool = True
    AGENT_PRESENCE_REDIS_URL: str | None = None
    AGENT_PRESENCE_TTL_SECONDS: int = 75
    AGENT_COMMAND_TIMEOUT_SECONDS: int = 45
    ALLOW_LEGACY_UNENROLLED_AGENTS: bool = False
    ALLOW_LEGACY_LOCAL_HOST_OPERATIONS: bool = True
    LEGACY_PUBLIC_USER_REGISTRATION_ENABLED: bool = False
    REGISTRATION_RATE_LIMIT_WINDOW_SECONDS: int = 3600
    REGISTRATION_RATE_LIMIT_MAX_ATTEMPTS: int = 10

    model_config = SettingsConfigDict(
        env_file=(str(PROJECT_ENV), str(BACKEND_ENV)),
        extra="ignore",
    )


settings = Settings()

SECRET_KEY = settings.SECRET_KEY
CREDENTIAL_ENCRYPTION_KEY = settings.CREDENTIAL_ENCRYPTION_KEY
MONGODB_URL = settings.MONGODB_URL
MONGODB_DATABASE = settings.MONGODB_DATABASE
MONGODB_CONNECT_TIMEOUT_MS = settings.MONGODB_CONNECT_TIMEOUT_MS
MONGODB_SOCKET_TIMEOUT_MS = settings.MONGODB_SOCKET_TIMEOUT_MS
MONGODB_WAIT_QUEUE_TIMEOUT_MS = settings.MONGODB_WAIT_QUEUE_TIMEOUT_MS
MONGODB_MAX_POOL_SIZE = settings.MONGODB_MAX_POOL_SIZE
MONGODB_MIN_POOL_SIZE = settings.MONGODB_MIN_POOL_SIZE
MONGODB_MAX_IDLE_TIME_MS = settings.MONGODB_MAX_IDLE_TIME_MS

GUACAMOLE_URL = settings.GUACAMOLE_URL
GUACAMOLE_PUBLIC_URL = settings.GUACAMOLE_PUBLIC_URL or settings.GUACAMOLE_URL
GUACAMOLE_USER = settings.GUACAMOLE_USER
GUACAMOLE_PASSWORD = settings.GUACAMOLE_PASSWORD
GUACAMOLE_DATA_SOURCE = settings.GUACAMOLE_DATA_SOURCE
GUACAMOLE_TOKEN_CACHE_SECONDS = settings.GUACAMOLE_TOKEN_CACHE_SECONDS
REMOTEAPP_BROWSER_LAUNCH_TTL_SECONDS = settings.REMOTEAPP_BROWSER_LAUNCH_TTL_SECONDS
GUACAMOLE_HTTP_POOL_SIZE = settings.GUACAMOLE_HTTP_POOL_SIZE
GUACAMOLE_CONNECT_TIMEOUT_SECONDS = settings.GUACAMOLE_CONNECT_TIMEOUT_SECONDS
GUACAMOLE_READ_TIMEOUT_SECONDS = settings.GUACAMOLE_READ_TIMEOUT_SECONDS
GUACAMOLE_VISUAL_QUALITY = settings.GUACAMOLE_VISUAL_QUALITY
GUACAMOLE_ENABLE_PRINTING = settings.GUACAMOLE_ENABLE_PRINTING
GUACAMOLE_PRINTER_NAME = settings.GUACAMOLE_PRINTER_NAME
GUACAMOLE_MAX_CONNECTIONS = settings.GUACAMOLE_MAX_CONNECTIONS
GUACAMOLE_MAX_CONNECTIONS_PER_USER = settings.GUACAMOLE_MAX_CONNECTIONS_PER_USER
PORTAL_HOME_URL = settings.PORTAL_HOME_URL
FRONTEND_URL = settings.FRONTEND_URL
LR_SERVER_URL = settings.LR_SERVER_URL
LR_BACKEND_URL = settings.LR_BACKEND_URL
RDP_PRECHECK_ENABLED = settings.RDP_PRECHECK_ENABLED
FILE_TRANSFER_ROOT = settings.FILE_TRANSFER_ROOT
FILE_TRANSFER_MAX_UPLOAD_BYTES = settings.FILE_TRANSFER_MAX_UPLOAD_BYTES
FILE_TRANSFER_MAX_READ_BYTES = settings.FILE_TRANSFER_MAX_READ_BYTES
ENVIRONMENT = settings.ENVIRONMENT
CORS_ORIGINS = settings.CORS_ORIGINS
SOCKETIO_CORS_ORIGINS = settings.SOCKETIO_CORS_ORIGINS
SOCKETIO_MESSAGE_QUEUE = settings.SOCKETIO_MESSAGE_QUEUE
SOCKETIO_ASYNC_MODE = settings.SOCKETIO_ASYNC_MODE
SOCKETIO_PING_INTERVAL_SECONDS = settings.SOCKETIO_PING_INTERVAL_SECONDS
SOCKETIO_PING_TIMEOUT_SECONDS = settings.SOCKETIO_PING_TIMEOUT_SECONDS
SOCKETIO_MAX_HTTP_BUFFER_BYTES = settings.SOCKETIO_MAX_HTTP_BUFFER_BYTES
PRINTING_ENABLED = settings.PRINTING_ENABLED
PRINTING_MAX_JOB_SIZE_MB = settings.PRINTING_MAX_JOB_SIZE_MB
PRINTING_JOB_TIMEOUT_SECONDS = settings.PRINTING_JOB_TIMEOUT_SECONDS
PRINTING_TEMP_RETENTION_SECONDS = settings.PRINTING_TEMP_RETENTION_SECONDS
PRINTING_DEFAULT_MODE = settings.PRINTING_DEFAULT_MODE
PRINTING_BROWSER_FALLBACK = settings.PRINTING_BROWSER_FALLBACK
PRINTING_CHUNK_SIZE = settings.PRINTING_CHUNK_SIZE
PRINTING_AUTOMATIC = settings.PRINTING_AUTOMATIC
PRINTING_ALLOWED_MODES = settings.PRINTING_ALLOWED_MODES
PRINTING_SPOOL_ROOT = settings.PRINTING_SPOOL_ROOT
LICENSE_VALIDATION_URL = settings.LICENSE_VALIDATION_URL
LICENSE_VALIDATION_TIMEOUT_SECONDS = settings.LICENSE_VALIDATION_TIMEOUT_SECONDS
TENANT_REGISTRATION_ENABLED = settings.TENANT_REGISTRATION_ENABLED
AGENT_ENROLLMENT_TOKEN_EXPIRY_SECONDS = settings.AGENT_ENROLLMENT_TOKEN_EXPIRY_SECONDS
AGENT_ENROLLMENT_REQUIRED = settings.AGENT_ENROLLMENT_REQUIRED
AGENT_REQUIRE_MACHINE_BINDING = settings.AGENT_REQUIRE_MACHINE_BINDING
AGENT_PRESENCE_REDIS_URL = settings.AGENT_PRESENCE_REDIS_URL
AGENT_PRESENCE_TTL_SECONDS = settings.AGENT_PRESENCE_TTL_SECONDS
AGENT_COMMAND_TIMEOUT_SECONDS = settings.AGENT_COMMAND_TIMEOUT_SECONDS
ALLOW_LEGACY_UNENROLLED_AGENTS = settings.ALLOW_LEGACY_UNENROLLED_AGENTS
ALLOW_LEGACY_LOCAL_HOST_OPERATIONS = settings.ALLOW_LEGACY_LOCAL_HOST_OPERATIONS
LEGACY_PUBLIC_USER_REGISTRATION_ENABLED = settings.LEGACY_PUBLIC_USER_REGISTRATION_ENABLED
REGISTRATION_RATE_LIMIT_WINDOW_SECONDS = settings.REGISTRATION_RATE_LIMIT_WINDOW_SECONDS
REGISTRATION_RATE_LIMIT_MAX_ATTEMPTS = settings.REGISTRATION_RATE_LIMIT_MAX_ATTEMPTS

from datetime import timedelta

SESSION_COOKIE_HTTPONLY = True
REMEMBER_COOKIE_HTTPONLY = True
REMEMBER_COOKIE_DURATION = timedelta(days=30)
SESSION_COOKIE_SAMESITE = "Lax"
REMEMBER_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = settings.ENVIRONMENT == "production" or settings.FLASK_ENV == "production"
REMEMBER_COOKIE_SECURE = SESSION_COOKIE_SECURE
PREFERRED_URL_SCHEME = "https" if SESSION_COOKIE_SECURE else "http"

